version: '3.9'

services:
  nginx:
    image: nginx:${NGINX_VERSION}
    env_file:
      - ".env"
    ports:
      - "${NGINX_EXPOSED_PORT}80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    networks:
      - app-n-p-m-r

  php-fpm:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./php/config/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php:/var/www/html
      - ./php/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
    env_file:
      - ".env"
    environment:
      - TEST_DB_HOST=${MYSQL_HOST}
      - TEST_DB_NAME=${MYSQL_DATABASE}
      - TEST_DB_USER=${MYSQL_ROOT_USER}
      - TEST_DB_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - app-n-p-m-r

  mysql-db:
    image: mysql:${MYSQL_VERSION}
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "${MYSQL_EXPOSED_PORT}3306" 
    networks:
      - app-n-p-m-r

  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    ports:
      - "${REDIS_EXPOSED_PORT}6379"
    networks:
      - app-n-p-m-r

networks:
  app-n-p-m-r:
    driver: bridge
